print("Welcome to the Band Name Generator")
print("What's the name of the city you grew up in?")
city = input()
print(city)
print("What's your pet's name?")
pet_name = input()
print(pet_name)
print('Your band name could be {}'.format(city + "'s " + pet_name))
